/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DesainAdmin;

import eraport.database;
import eraport.guru;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fery
 */
public class TampilGuru extends javax.swing.JFrame {

    /**
     * Creates new form Hapusguru
     */
    public TampilGuru() {
        initComponents();
        loadguru();
    }
    
    public void loadguru()
    {
         DefaultTableModel model = (DefaultTableModel) tabguru.getModel();
         database d = new eraport.database();
         database da = new eraport.database();
        try {
            String s = "select nip,nama,mapel from guru ";
            
            
            da.getdata(s);
            int i =0,j=0;
            while(da.rs.next()){
                j++;
            }
            model.setRowCount(j);
            d.getdata(s);
            while(d.rs.next()){
                tabguru.setValueAt(d.rs.getString("nip"), i, 0);
                tabguru.setValueAt(d.rs.getString("nama"), i, 1);
                tabguru.setValueAt(d.rs.getString("mapel"), i, 2);
                
                i++;
            }
        } catch (Exception e) {
        }
        tabguru.setAutoCreateRowSorter(true);
    }
    
    
             
             

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nip_cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabguru = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo Tut Wuri Handayani (redesign 2012 by Rahmintama).png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("SMA NEGERI KEBAKKRAMAT");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("KARANGANYAR");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Jl. Nangsri Kebakkramat Karanganyar 57762");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Cari NIP");

        nip_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nip_cariActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("Refresh Table");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nip_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nip_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabguru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Guru Mapel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabguru);
        if (tabguru.getColumnModel().getColumnCount() > 0) {
            tabguru.getColumnModel().getColumn(0).setMinWidth(150);
            tabguru.getColumnModel().getColumn(0).setMaxWidth(200);
            tabguru.getColumnModel().getColumn(1).setMinWidth(230);
            tabguru.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       EditGuru eg = new DesainAdmin.EditGuru();
       eg.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabguru.getModel();
        model.setRowCount(1);
        database e = new eraport.database();
                String s = "select nip,nama,mapel from guru where nip='"+nip_cari.getText()+"'";
           try
           {
                e.rs = e.getdata(s);
                if(e.rs.next()){
                    JOptionPane.showMessageDialog(null, "Data Found");
                    
                    tabguru.setValueAt(e.rs.getString("nip"), 0, 0);
                    tabguru.setValueAt(e.rs.getString("nama"), 0, 1);
                    tabguru.setValueAt(e.rs.getString("mapel"), 0, 2);
                    
               
            }
            else{
                JOptionPane.showMessageDialog(null, "Data not found");
            }
           }    
            
            catch (SQLException f) {
            javax.swing.JOptionPane.showMessageDialog(null,"Error"+f.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        loadguru();
    }//GEN-LAST:event_jButton5ActionPerformed
 guru g = new eraport.guru();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int indeks;
        indeks=tabguru.getSelectedRow();
        String nip=tabguru.getModel().getValueAt(indeks,0).toString();
        
       
         try {
            g.deleteguru(nip);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
        loadguru();
        
       
           
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int indeks;
        indeks=tabguru.getSelectedRow();
        String nip=tabguru.getModel().getValueAt(indeks,0).toString();
        
        database e = new eraport.database();
                String s = "select * from guru where nip='"+nip+"'";
           try
           {
                e.rs = e.getdata(s);
                if(e.rs.next()){
                    JOptionPane.showMessageDialog(null, "Data Found");
                     TambahGuru tg = new TambahGuru();
                    tg.setVisible(true);
        
                    tg.create_nip.setText(e.rs.getString("nip"));
                    tg.create_nip.disable();
                    tg.create_nama.setText(e.rs.getString("nama"));
                    tg.create_alamat.setText(e.rs.getString("alamat"));
                    tg.create_telp.setText(e.rs.getString("telp"));
                    tg.create_email.setText(e.rs.getString("email"));
                    tg.create_tempatlahir.setText(e.rs.getString("tempat_lahir"));
                    tg.create_tanggal.setSelectedIndex(0);
                    tg.create_bulan.setSelectedIndex(0);
                    tg.create_tahun.setSelectedIndex(0);
                    int agama=0;
                    if("Islam".equals(e.rs.getString("agama")))
                    {
                        agama=0;
                    }
                    else if("Kristen".equals(e.rs.getString("agama")))
                    {
                        agama=1;
                    }
                    else if("Katholik".equals(e.rs.getString("agama")))
                    {
                        agama=2;
                    }
                    else if("Hindu".equals(e.rs.getString("agama")))
                    {
                        agama=3;
                    }
                    else if("Budha".equals(e.rs.getString("agama")))
                    {
                        agama=4;
                    }
                    tg.create_agama.setSelectedIndex(agama);
                    
                    int status=0;
                    if("Menikah".equals(e.rs.getString("status")))
                    {
                        status=0;
                    }
                    else if("Belum Menikah".equals(e.rs.getString("status")))
                    {
                        status=1;
                    }
                    tg.create_status.setSelectedIndex(status);
                    
                    int jk=0;
                    if("Laki-laki".equals(e.rs.getString("jk")))
                    {
                        jk=0;
                    }
                    else if("Perempuan".equals(e.rs.getString("jk")))
                    {
                        jk=1;
                    }
                    tg.create_jeniskelamin.setSelectedIndex(jk);
                    
                    int mapel=0;
                    if("Matematika".equals(e.rs.getString("mapel")))
                    {
                        mapel=0;
                    }
                    else if("Bahasa Indonesia".equals(e.rs.getString("mapel")))
                    {
                        mapel=1;
                    }
                    else if("Fisika".equals(e.rs.getString("mapel")))
                    {
                        mapel=2;
                    }
                    else if("Biologi".equals(e.rs.getString("mapel")))
                    {
                        mapel=3;
                    }
                    else if("Kimia".equals(e.rs.getString("mapel")))
                    {
                        mapel=4;
                    }
                    else if("Bahasa Inggris".equals(e.rs.getString("mapel")))
                    {
                        mapel=5;
                    }
                    else if("Geografi".equals(e.rs.getString("mapel")))
                    {
                        mapel=6;
                    }
                    else if("Sosiologi".equals(e.rs.getString("mapel")))
                    {
                        mapel=7;
                    }
                    else if("Akuntansi".equals(e.rs.getString("mapel")))
                    {
                        mapel=8;
                    }
                    else if("Olahraga".equals(e.rs.getString("mapel")))
                    {
                        mapel=9;
                    }
                    tg.create_mapel.setSelectedIndex(1);
            }
            else{
                JOptionPane.showMessageDialog(null, "Data not found");
            }
           }    
            
            catch (SQLException f) {
            javax.swing.JOptionPane.showMessageDialog(null,"Error"+f.getMessage());
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nip_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nip_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nip_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        guru g = new eraport.guru();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilGuru().setVisible(true);
               
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nip_cari;
    public javax.swing.JTable tabguru;
    // End of variables declaration//GEN-END:variables
}
